---

- name: Set new release as current
  file:
    src: "{{ new_release_dir }}"
    dest: "{{ current_dir }}"
    state: link
    force: true
  # notify: Restart php-fpm

- name: Restart php-fpm
  service:
    name: php7.2-fpm
    state: reloaded
  become: true
  when: restart_fpm
