---

- name: Check if vendor directory exists
  stat:
    path: "{{ latest_release.path }}/vendor"
  register: latest_vendor_directory_stat
  when:  latest_release is defined

- name: Copy vendor
  shell: cp -r -p "{{ latest_release.path }}/vendor" "{{ new_release_dir }}/vendor"
  when: copy_vendor and latest_release is defined and latest_vendor_directory_stat.stat.exists == true

- name: Install composer deps
  composer:
    command: install
    working_dir: "{{ new_release_dir }}"
    prefer_dist: true
    optimize_autoloader: true
    no_dev: true
    no_scripts: true
