---

- name: Remove new release storage dir
  file:
    path: "{{ new_release_dir }}/storage"
    state: absent

- name: Link new release storage directory to persistent/storage
  file:
    src: "{{ persistent_dir }}/storage"
    dest: "{{ new_release_dir }}/storage"
    state: link
