---

- name: Rollback migrations
  shell: "{{ migrate_rollback_command | default('php artisan migrate:rollback --force') }}"
  args:
    chdir: "{{ new_release_dir }}"
  when: migrate and migrations_output is defined and migrations_output.stdout.find('Nothing to migrate.') == -1

- name: Remove new release
  file:
    path: "{{ new_release_dir }}"
    state: absent

- name: Restore latest successful release
  file:
    src: "{{ latest_release.path }}"
    dest: "{{ current_dir }}"
    state: link
    force: true
  when: latest_release is defined
